### ISSUE TITLE
Status, Categories etc. need scrolling unlike the default scheme

### ISSUE THREAD

**Issue by stephen147** [jagannatharjun/qbt-theme#10] opened 2020-03-29 14:40 UTC
**Same issue as this:** (Which has been fixed)
https://github.com/maboroshin/qBittorrentDarktheme/issues/4

### Relates to the `darkstylesheet.qbtheme`

In the default scheme all the top 3 items, status, categories and tags show without the need for scrolling each of them.

Theme tested here: ayuDark.qbtheme

### Issue with theme
![qSHuYnCAjG](https://user-images.githubusercontent.com/14054664/77483559-5a3a4b00-6e20-11ea-8a77-855781ea334a.png)

### Default theme. They're all in the same view as shown here:
![Ax9m5o1MlE](https://user-images.githubusercontent.com/14054664/77483564-5c9ca500-6e20-11ea-89a4-50250646fc47.png)

**Comment by maboroshin** [comment] 2020-03-31 00:24
The problem caused by "min-height". It was fixed by delete.
```
QAbstractScrollArea {
  min-height: 1.25em;
}
```

**Comment by jagannatharjun** [comment] 2020-04-04 17:47
@maboroshin  thanks for the fix

**Closed by jagannatharjun** 2020-04-04 17:47 UTC
