### ISSUE TITLE
Buttons click hitbox when using mumble dark theme considers only the labels and icons instead of the whole button area.

### ISSUE THREAD

**Issue by MrBridgeSix** [jagannatharjun/qbt-theme#34] opened 2020-11-06 18:41 UTC

**Comment by ryanhossain9797** [comment] 2020-11-07 13:58
To elaborate on this a bit, if you click the `[_ok_]` button you have to click in the center on the text, the empty space around it can't be clicked.

**Comment by alperc84** [comment] 2020-11-13 06:36
Duplicate of #31

**Closed** 2020-11-22 05:36 UTC
